version: '3.4'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: aggregates
      POSTGRES_DB: aggregates
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql